# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtnormrej <- function(mu, sd, l, r) {
    .Call('_powreg_rtnormrej', PACKAGE = 'powreg', mu, sd, l, r)
}

rshiftexp <- function(d, t) {
    .Call('_powreg_rshiftexp', PACKAGE = 'powreg', d, t)
}

remcol <- function(A, i) {
    .Call('_powreg_remcol', PACKAGE = 'powreg', A, i)
}

remrow <- function(a, i) {
    .Call('_powreg_remrow', PACKAGE = 'powreg', a, i)
}

sampleBeta <- function(start, DUty, delta, d, Vt, sigsq, W) {
    .Call('_powreg_sampleBeta', PACKAGE = 'powreg', start, DUty, delta, d, Vt, sigsq, W)
}

sampleGamma <- function(beta, tausq, q) {
    .Call('_powreg_sampleGamma', PACKAGE = 'powreg', beta, tausq, q)
}

sampler <- function(DUty, Vt, d, W, sigsq, tausq, q, samples, start, seed, burn, thin) {
    .Call('_powreg_sampler', PACKAGE = 'powreg', DUty, Vt, d, W, sigsq, tausq, q, samples, start, seed, burn, thin)
}

